apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: development
  labels:
    app: mongo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongo
      labels:
        app: mongo
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name:  MONGO_INITDB_ROOT_PASSWORD
              value: example
          volumeMounts:
            - name: persistent-storage
              mountPath: /mongo/data
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: mongo-ebs-claim

