apiVersion: v1
kind: Service
metadata:
  name: mongo-cluster-ip
  namespace: development
  labels:
    app: mongo
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo
