services:
  redis:
    container_name: redis
    image: redis:latest
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: someredispassword
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - backend

  backend-app:
    container_name: backend-app
    image: kholha/expency-backend:latest
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: someredispassword
    ports:
      - "8706:8706"
    depends_on:
      - mongo
      - redis
    networks:
      - backend

  frontend-app:
    container_name: frontend-app
    image: kholha/expency-frontend:latest
    environment:
      NEXT_APP_API_KEY: fergdhkdskgldkdd
    ports:
      - "3000:3000"
    depends_on:
      - backend-app
      - mongo
      - redis
    networks:
      - frontend

volumes:
  mongo-data:
  redis-data:

networks:
  frontend:
  backend: