---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend-pods
      labels: 
        app: frontend
    spec:
      containers:
        - name: frontend
          image: annika1712/frontend:v1
          ports:
            - containerPort: 80
  