apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: development
  labels:
    app: backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: kholha/expency-backend:latest
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: PORT
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: REDIS_PASSWORD
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DATABASE_URI
          ports:
            - containerPort: 8706
