apiVersion: v1
kind: Service
metadata:
  name: load-balancer-backend
  namespace: development
  labels:
    app.kubernetes.io/name: load-balancer-backend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8706
      name: http
  selector:
    app: backend