apiVersion: v1
kind: Service
metadata:
  name: backend-lb-service
#  namespace: development
spec:
  selector:
    app: backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8706
      targetPort: 8706
      nodePort: 31000