---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: development
  labels:
    app: frontend
spec:
  replicas: 4
  selector:
    matchLabels: 
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: kholha/expency-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: next-public-api-url
              valueFrom:
                configMapKeyRef:
                  name: frontend-config-dev
                  key: NEXT_PUBLIC_API_URL
            - name: next-app-api-key
              valueFrom:
                secretKeyRef:
                  name: frontend-secret-dev
                  key: NEXT_APP_API_KEY