---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: development
  labels:
    app: frontend
spec:
  replicas: 4
  selector:
    matchLabels: 
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: annika1712/exp-frontend
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: NEXT_PUBLIC_API_URL
            - name: NEXT_APP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: frontend-secret
                  key: NEXT_APP_API_KEY