apiVersion: v1
kind: Service
metadata:
  name: load-balancer-frontend
  namespace: development
  labels:
    app.kubernetes.io/name: load-balancer-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      name: http
  selector:
    app: frontend