apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configs
#  namespace: development
data:
  public_api_url: "http://aa8fd6c92e1314e2c81c4191041e5476-1537797463.us-east-1.elb.amazonaws.com:8706"