apiVersion: v1
kind: Service
metadata:
  name: frontend-lb-service
#  namespace: development
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000