apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: development
  labels:
    app: redis
#    app.kubernetes.io/created-by: team-1
#    app.kubernetes.io/type: app
#    app.kubernetes.io/name: redis
#    app.kubernetes.io/component: database
spec:
  replicas: 4
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
#          resources:
#            requests:
#              cpu: 100m
#              memory: 100Mi
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: persistent-storage
              mountPath: /redis/data
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: redis-ebs-claim
