name: deploy
on:
  push:
    branches: [ "annika/ci-cd" ]
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs: 
  deploy:
    name: deploy

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        role-to-assume: arn:aws:iam::851725332718:role/eks_github_oidc-team-1-fp-eks-9deZbI34
        aws-region: eu-central-1
        role-session-name: GithubActionsSession

    - name: Install aws CLI
      run: aws eks update-kubeconfig --region eu-central-1 --name team-1-fp-eks-9deZbI34 --role-arn arn:aws:iam::851725332718:role/eks_github_oidc-team-1-fp-eks-9deZbI34

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      id: install

    - run: kubectl config set-context --current --namespace=development

    - name: Alter configmap and apply
      run: |
        kubectl apply -f /kubernetes/ingress
        sleep 30s
        export BACKEND_HOSTNAME=$(kubectl -n annika get svc backend-lb -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
        envsubst < /kubernetes/frontend/frontend-configmap.yml | kubectl apply -f -
    
    - name: Apply kubernetes manifest files
      run: |
        kubectl apply -f /kubernetes/mongodb/
        kubectl apply -f /kubernetes/redis/
        kubectl apply -f /kubernetes/backend/
        kubectl apply -f /kubernetes/frontend/
    
    
