name: Build and Publish backend with Docker

on:
  push:
    branches: [ "devs" ]
#    paths:
#      - 'backend/*'

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build UI image and push to DockerHub
      - name: Build and push backend application
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: "{{defaultContext}}:backend"
          push: true
          tags: |
            annika1712/exp-backend:latest
            annika1712/exp-backend:1.0.0