name: Build and Publish frontend with Docker

on:
  push:
    branches: [ "annika/ci-cd" ]
#    paths:
#     - 'frontend/*'

env:
  RELEASE_VERSION: 

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            annika1712/exp-frontend
          tags: |
            tags: |
            # set latest tag for default branch
            type=raw,pattern=v{{major}},enable={{is_default_branch}}
            type=semver,pattern={{version}}
          flavor: latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build UI image and push to DockerHub
      - name: Build and push frontend application
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: "{{defaultContext}}:frontend"
          push: true
          tags: ${{ steps.meta.outputs.tags }}

